### ISSUE TITLE
如何设置候选表情的数量,比如只显示两三个?

### ISSUE THREAD

**Issue by realysy** [rtransformation/rime-opencc_emoji_symbols#4]
现在显示太多了,如果要输入的字有对应表情的话,翻好多页才能找到字.

**Comment by rtransformation** [comment]
不好意思，回复晚了，一直没注意有人开了issue😂，是这样：
①如果您觉得有好多Emoji您是用不到的，可以自行裁剪一部分。做一个适合自己的。
②可以选择临时关闭Emoji选项，如下设置：
在你的方案的schema里
key_binder:
  bindings:
    - {accept: "Control+Shift+E", toggle: show_es, when: always} #显示或关闭Emoji和符号
当然，这个快捷键您可以替换成别的。

因为我本人是打五笔的，所以基本没有要翻页找字的情况，就没有考虑过这个问题。
