### ISSUE TITLE
双拼下部分emoji无法拼写

### ISSUE THREAD

**Issue by mikelyou** [rtransformation/rime-opencc_emoji_symbols#5]
非常感谢开发者，这个真的很好用！

我是双拼用户，在遇到 `tsu`  `ppm` 这种英文组合时没有办法打出来，当然 `英里` 这种中文的没有问题。想请问一下，有没有方法可以解决这个问题？本人对代码一知半解，能读懂一些，这个问题我想不到要怎么办。不知道开发者是否有时间，但总之先表示感谢了。:smile: ❤️

**Comment by rtransformation** [comment]
> 

你可以在es.txt裏面把對應的詞條刪掉。
