### ISSUE TITLE
相同编码候选太多影响正常输入

### ISSUE THREAD

**Issue by Jacobax** [rtransformation/rime-opencc_emoji_symbols#9]
比如xiao，候选数设置为5情况下，前6页只有笑和小两个字，其它全是表情
只能临时开关
如果不影响正常输入就不用经常开关省心了

**Comment by rtransformation** [comment]
> 

我这个就是尽可能把表情收集全了，因为我自己是打五笔的，所以基本上没有重码困扰，所以我才把表情都弄得这么全，找起表情来方便。

对于拼音用户来说，如果觉得有些地方影响输入了，那就自己把常用到的那些自行删减一下就好啦。
